USE ORG;

SELECT FIRST_NAME AS WORKER_NAME FROM WORKER;

SELECT UPPER(FIRST_NAME) FROM WORKER;

SELECT distinct DEPARTMENT FROM WORKER;

SELECT DEPARTMENT, COUNT(DEPARTMENT) FROM WORKER GROUP BY DEPARTMENT;

SELECT SUBSTRING(FIRST_NAME,1,3) FROM WORKER;

SELECT INSTR(FIRST_NAME, 'H') FROM WORKER WHERE FIRST_NAME = 'NIHARIKA';

SELECT rtrim(FIRST_NAME) FROM WORKER ;

SELECT DISTINCT DEPARTMENT, LENGTH(DEPARTMENT) FROM WORKER;

SELECT replace(FIRST_NAME , 'A', 'a') FROM WORKER;

SELECT concat(FIRST_NAME, ' ', LAST_NAME) AS COMPLETE_NAME FROM WORKER;

SELECT * FROM WORKER ORDER BY FIRST_NAME;

SELECT * FROM WORKER ORDER BY FIRST_NAME, DEPARTMENT DESC;

SELECT * FROM WORKER WHERE FIRST_NAME IN( 'NIHARIKA','DHRUV');  

SELECT * FROM WORKER WHERE FIRST_NAME NOT IN ('NIHARIKA', 'DHRUV');

SELECT * FROM WORKER WHERE DEPARTMENT LIKE 'ADMIN%';

SELECT * FROM WORKER WHERE FIRST_NAME LIKE '%A%';

SELECT * FROM WORKER WHERE FIRST_NAME LIKE '%A';

SELECT * FROM WORKER WHERE FIRST_NAME LIKE '_____A%';

SELECT *FROM WORKER WHERE SALARY BETWEEN 10000 AND 500000;

SELECT * FROM WORKER WHERE YEAR(JOINING_DATE) = 2014 AND MONTH(JOINING_DATE) =02;

SELECT DEPARTMENT, COUNT(*) FROM WORKER WHERE DEPARTMENT = 'ADMIN';

SELECT CONCAT(FIRST_NAME,' ', LAST_NAME) FROM WORKER WHERE SALARY BETWEEN 10000 AND 500000;

SELECT * FROM WORKER ORDER BY FIRST_NAME;

SELECT * FROM WORKER ORDER BY FIRST_NAME, DEPARTMENT DESC;

SELECT * FROM WORKER WHERE FIRST_NAME IN( 'NIHARIKA','DHRUV');  

SELECT * FROM WORKER WHERE FIRST_NAME NOT IN ('NIHARIKA', 'DHRUV');

SELECT * FROM WORKER WHERE DEPARTMENT LIKE 'ADMIN%';

SELECT * FROM WORKER WHERE FIRST_NAME LIKE '%A%';

SELECT * FROM WORKER WHERE FIRST_NAME LIKE '%A';

SELECT * FROM WORKER WHERE FIRST_NAME LIKE '_____A%';

SELECT *FROM WORKER WHERE SALARY BETWEEN 10000 AND 500000;

SELECT * FROM WORKER WHERE YEAR(JOINING_DATE) = 2014 AND MONTH(JOINING_DATE) =02;

SELECT DEPARTMENT, COUNT(*) FROM WORKER WHERE DEPARTMENT = 'ADMIN';

SELECT CONCAT(FIRST_NAME,' ', LAST_NAME) FROM WORKER WHERE SALARY BETWEEN 10000 AND 500000;

SELECT DEPARTMENT, count(WORKER_ID) AS NO_OF_WORKER FROM WORKER group by DEPARTMENT ORDER BY COUNT(WORKER_ID) ;

SELECT WORKER_TITLE, COUNT(*) FROM TITLE GROUP BY WORKER_TITLE HAVING COUNT(*) > 1;


CREATE TABLE WORKER_CLONE LIKE WORKER;
INSERT INTO WORKER_CLONE SELECT *FROM WORKER;
SELECT * FROM WORKER_CLONE;

SELECT CURDATE();
SELECT NOW();

SELECT * FROM WORKER ORDER BY SALARY DESC LIMIT 4,1;

SELECT SALARY FROM WORKER W1
WHERE 4 =(

SELECT COUNT(DISTINCT (W2.SALARY))
FROM WORKER W2
WHERE W2. SALARY >= W1.SALARY
);

SELECT MAX(SALARY) FROM WORKER WHERE SALARY NOT IN (SELECT max(SALARY) FROM WORKER);

SELECT * FROM WORKER
UNION 
SELECT * FROM WORKER ORDER BY WORKER_ID;

SELECT WORKER_ID FROM WORKER WHERE WORKER_ID NOT IN ( SELECT WORKER_REF_ID FROM BONUS);

SELECT*FROM WORKER WHERE WORKER_ID <=(select  COUNT(WORKER_ID)/2 FROM WORKER);

SELECT DEPARTMENT, count(DEPARTMENT) AS depcount FROM WORKER GROUP BY DEPARTMENT HAVING depcount<4;

select *from WORKER WHERE WORKER_ID = (SELECT MAX(WORKER_ID)FROM WORKER);

SELECT * FROM WORKER ORDER BY WORKER_ID DESC LIMIT 5;

SELECT * FROM WORKER ORDER BY WORKER_ID LIMIT 5;

(SELECT * FROM WORKER ORDER BY WORKER_ID DESC LIMIT 5) order by WORKER_ID;

SELECT MAX(SALARY) AS MAXSAL, DEPARTMENT FROM WORKER GROUP BY DEPARTMENT ;

SELECT distinct SALARY FROM WORKER  W1
WHERE 3>= (SELECT COUNT(DISTINCT SALARY) FROM WORKER W2 WHERE W1.SALARY <= W2.SALARY) ORDER BY SALARY DESC;

SELECT DEPARTMENT, SUM(SALARY) AS DEPSAL FROM WORKER GROUP BY DEPARTMENT ORDER BY DEPSAL DESC;

SELECT FIRST_NAME, SALARY FROM WORKER WHERE SALARY = (SELECT max(SALARY) FROM WORKER);





