USE ORG;

SELECT FIRST_NAME AS WORKER_NAME FROM WORKER;

SELECT UPPER(FIRST_NAME) FROM WORKER;

SELECT distinct DEPARTMENT FROM WORKER;

SELECT DEPARTMENT, COUNT(DEPARTMENT) FROM WORKER GROUP BY DEPARTMENT;

SELECT SUBSTRING(FIRST_NAME,1,3) FROM WORKER;

SELECT INSTR(FIRST_NAME, 'H') FROM WORKER WHERE FIRST_NAME = 'NIHARIKA';

SELECT rtrim(FIRST_NAME) FROM WORKER ;

SELECT DISTINCT DEPARTMENT, LENGTH(DEPARTMENT) FROM WORKER;

SELECT replace(FIRST_NAME , 'A', 'a') FROM WORKER;

SELECT concat(FIRST_NAME, ' ', LAST_NAME) AS COMPLETE_NAME FROM WORKER;

SELECT * FROM WORKER ORDER BY FIRST_NAME;

SELECT * FROM WORKER ORDER BY FIRST_NAME, DEPARTMENT DESC;

SELECT * FROM WORKER WHERE FIRST_NAME IN( 'NIHARIKA','DHRUV');  

SELECT * FROM WORKER WHERE FIRST_NAME NOT IN ('NIHARIKA', 'DHRUV');

SELECT * FROM WORKER WHERE DEPARTMENT LIKE 'ADMIN%';

SELECT * FROM WORKER WHERE FIRST_NAME LIKE '%A%';

SELECT * FROM WORKER WHERE FIRST_NAME LIKE '%A';

SELECT * FROM WORKER WHERE FIRST_NAME LIKE '_____A%';

SELECT *FROM WORKER WHERE SALARY BETWEEN 10000 AND 500000;

SELECT * FROM WORKER WHERE YEAR(JOINING_DATE) = 2014 AND MONTH(JOINING_DATE) =02;

SELECT DEPARTMENT, COUNT(*) FROM WORKER WHERE DEPARTMENT = 'ADMIN';

SELECT CONCAT(FIRST_NAME,' ', LAST_NAME) FROM WORKER WHERE SALARY BETWEEN 10000 AND 500000;





